### ISSUE TITLE
4th July peer-to-peer

### ISSUE THREAD

**Issue by Zilola-Nazarova** [GeekyHacks/AwesomeBook#3]
## Highlights 💯 

- "Add" button works as expected;
- "Remove" button works as expected;

## Improvement suggestions ♻️ 
You could change the behaviour of your "Add" functionality:

the book will be added to the top of the list if you change:
- the [array.push()](https://github.com/GeekyHacks/AwesomeBook/blob/main/JS/script.js#L31) to array.unshift() ([the link to documentation](https://www.w3schools.com/jsref/jsref_unshift.asp));
- the [appendChild()](https://github.com/GeekyHacks/AwesomeBook/blob/main/JS/script.js#L19C5-L19C36) to insertBefore() ([the link to documentation](https://stackoverflow.com/questions/2007357/how-to-set-dom-element-as-first-child));

**Comment by GeekyHacks** [comment]
Well noted, you never cease to impress everyone with your knowledge and professional approach.
